[project]
name = "debut-memorizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-pymongo>=3.0.1",
    "python-chess>=1.999",
]
